export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_CLEAR_ITEMS = 'CART_RESET';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_INCREASE_QUANTITY = 'CART_INCREASE_QUANTITY';
export const CART_DECREASE_QUANTITY = 'CART_DECREASE_QUANTITY';
