export const GET_INVENTORIES_REQUEST = 'GET_INVENTORIES_REQUEST';
export const GET_INVENTORIES_SUCCESS = 'GET_INVENTORIES_SUCCESS';
export const GET_INVENTORIES_FAIL = 'GET_INVENTORIES_FAIL';
export const GET_INVENTORIES_RESET = 'GET_INVENTORIES_RESET';

export const GET_INVENTORY_REQUEST = 'GET_INVENTORY_REQUEST';
export const GET_INVENTORY_SUCCESS = 'GET_INVENTORY_SUCCESS';
export const GET_INVENTORY_FAIL = 'GET_INVENTORY_FAIL';
export const GET_INVENTORY_RESET = 'GET_INVENTORY_RESET';

export const CREATE_INVENTORY_REQUEST = 'CREATE_INVENTORY_REQUEST';
export const CREATE_INVENTORY_SUCCESS = 'CREATE_INVENTORY_SUCCESS';
export const CREATE_INVENTORY_FAIL = 'CREATE_INVENTORY_FAIL';
export const CREATE_INVENTORY_RESET = 'CREATE_INVENTORY_RESET';

export const UPDATE_INVENTORY_REQUEST = 'UPDATE_INVENTORY_REQUEST';
export const UPDATE_INVENTORY_SUCCESS = 'UPDATE_INVENTORY_SUCCESS';
export const UPDATE_INVENTORY_FAIL = 'UPDATE_INVENTORY_FAIL';
export const UPDATE_INVENTORY_RESET = 'UPDATE_INVENTORY_RESET';

export const DELETE_INVENTORY_REQUEST = 'DELETE_INVENTORY_REQUEST';
export const DELETE_INVENTORY_SUCCESS = 'DELETE_INVENTORY_SUCCESS';
export const DELETE_INVENTORY_FAIL = 'DELETE_INVENTORY_FAIL';
export const DELETE_INVENTORY_RESET = 'DELETE_INVENTORY_RESET';


export const GET_INVENTORIES_STATS = 'GET_INVENTORIES_STATS';
export const GET_INVENTORIES_BY_CATEGORY = 'GET_INVENTORIES_BY_CATEGORY';








