export const GET_RESERVATIONS_REQUEST = 'GET_RESERVATIONS_REQUEST';
export const GET_RESERVATIONS_SUCCESS = 'GET_RESERVATIONS_SUCCESS';
export const GET_RESERVATIONS_FAIL = 'GET_RESERVATIONS_FAIL';
export const GET_RESERVATIONS_RESET = 'GET_RESERVATIONS_RESET';

export const GET_RESERVATION_REQUEST = 'GET_RESERVATION_REQUEST';
export const GET_RESERVATION_SUCCESS = 'GET_RESERVATION_SUCCESS';
export const GET_RESERVATION_FAIL = 'GET_RESERVATION_FAIL';
export const GET_RESERVATION_RESET = 'GET_RESERVATION_RESET';

export const CREATE_RESERVATION_REQUEST = 'CREATE_RESERVATION_REQUEST';
export const CREATE_RESERVATION_SUCCESS = 'CREATE_RESERVATION_SUCCESS';
export const CREATE_RESERVATION_FAIL = 'CREATE_RESERVATION_FAIL';
export const CREATE_RESERVATION_RESET = 'CREATE_RESERVATION_RESET';

export const UPDATE_RESERVATION_REQUEST = 'UPDATE_RESERVATION_REQUEST';
export const UPDATE_RESERVATION_SUCCESS = 'UPDATE_RESERVATION_SUCCESS';
export const UPDATE_RESERVATION_FAIL = 'UPDATE_RESERVATION_FAIL';
export const UPDATE_RESERVATION_RESET = 'UPDATE_RESERVATION_RESET';

export const DELETE_RESERVATION_REQUEST = 'DELETE_RESERVATION_REQUEST';
export const DELETE_RESERVATION_SUCCESS = 'DELETE_RESERVATION_SUCCESS';
export const DELETE_RESERVATION_FAIL = 'DELETE_RESERVATION_FAIL';
export const DELETE_RESERVATION_RESET = 'DELETE_RESERVATION_RESET';
